extension Button {
  /// Compact text guaranteed to render on every supported macOS version.
  public var compactLabel: String {
    switch self {
    case .a: "A"
    case .b: "B"
    case .x: "X"
    case .y: "Y"
    case .leftBumper: "LB"
    case .rightBumper: "RB"
    case .l1: "L1"
    case .r1: "R1"
    case .leftStick: "L3"
    case .rightStick: "R3"
    case .start: "Start"
    case .options: "Opt"
    case .back: "Back"
    case .share: "Share"
    case .guide: "Guide"
    case .ps: "PS"
    case .dpadUp: "↑"
    case .dpadDown: "↓"
    case .dpadLeft: "←"
    case .dpadRight: "->"
    case .cross: "×"
    case .circle: "○"
    case .square: "□"
    case .triangle: "△"
    case .l2Digital: "L2"
    case .r2Digital: "R2"
    case .touchpad: "TP"
    case .leftGrip: "LG"
    case .rightGrip: "RG"
    case .leftPadClick: "LP"
    case .rightPadClick: "RP"
    case .leftSL: "L SL"
    case .leftSR: "L SR"
    case .rightSL: "R SL"
    case .rightSR: "R SR"
    case .leftFunction: "L Fn"
    case .rightFunction: "R Fn"
    case .leftPaddle: "L P"
    case .rightPaddle: "R P"
    case .mute: "Mute"
    }
  }

  /// SF Symbol name used by controller input presentation.
  public var systemImageName: String {
    switch self {
    case .a: "a.circle"
    case .b: "b.circle"
    case .x: "x.circle"
    case .y: "y.circle"
    case .leftBumper: "l1.button.roundedbottom.horizontal"
    case .rightBumper: "r1.button.roundedbottom.horizontal"
    case .leftStick: "l.joystick.press.down"
    case .rightStick: "r.joystick.press.down"
    case .start: "line.3.horizontal.circle"
    case .back: "rectangle.on.rectangle.circle"
    case .guide: "house.circle"
    case .dpadUp: "dpad.up.filled"
    case .dpadDown: "dpad.down.filled"
    case .dpadLeft: "dpad.left.filled"
    case .dpadRight: "dpad.right.filled"
    case .cross: "xmark.circle"
    case .circle: "circle.circle"
    case .square: "square.circle"
    case .triangle: "triangle.circle"
    case .l1: "l1.button.roundedbottom.horizontal"
    case .r1: "r1.button.roundedbottom.horizontal"
    case .l2Digital: "l2.button.roundedtop.horizontal"
    case .r2Digital: "r2.button.roundedtop.horizontal"
    case .share: "square.and.arrow.up.circle"
    case .options: "ellipsis.circle"
    case .ps: "logo.playstation"
    case .touchpad: "rectangle.roundedtop"
    case .leftGrip, .rightGrip, .leftPadClick, .rightPadClick,
      .leftSL, .leftSR, .rightSL, .rightSR,
      .leftFunction, .rightFunction, .leftPaddle, .rightPaddle: "circle"
    case .mute: "mic.slash.circle"
    }
  }

  /// A short, human-readable label for the button (e.g. `"Left Bumper (LB)"`).
  ///
  /// Used in the mapping editor and profile display.
  public var displayName: String {
    switch self {
    case .a: "A"
    case .b: "B"
    case .x: "X"
    case .y: "Y"
    case .leftBumper: "Left Bumper (LB)"
    case .rightBumper: "Right Bumper (RB)"
    case .leftStick: "Left Stick Click (LSB)"
    case .rightStick: "Right Stick Click (RSB)"
    case .start: "Start / Menu"
    case .back: "Back / View"
    case .guide: "Guide / Home"
    case .dpadUp: "D-Pad Up"
    case .dpadDown: "D-Pad Down"
    case .dpadLeft: "D-Pad Left"
    case .dpadRight: "D-Pad Right"
    case .cross: "Cross (\u{00D7})"
    case .circle: "Circle (\u{25CB})"
    case .square: "Square (\u{25A1})"
    case .triangle: "Triangle (\u{25B3})"
    case .l1: "L1"
    case .r1: "R1"
    case .l2Digital: "L2 (Digital)"
    case .r2Digital: "R2 (Digital)"
    case .share: "Share"
    case .options: "Options"
    case .ps: "PS Button"
    case .touchpad: "Touchpad Click"
    case .leftGrip: "Left grip"
    case .rightGrip: "Right grip"
    case .leftPadClick: "Left pad click"
    case .rightPadClick: "Right pad click"
    case .leftSL: "Left Joy-Con SL"
    case .leftSR: "Left Joy-Con SR"
    case .rightSL: "Right Joy-Con SL"
    case .rightSR: "Right Joy-Con SR"
    case .leftFunction: "Left function button"
    case .rightFunction: "Right function button"
    case .leftPaddle: "Left paddle"
    case .rightPaddle: "Right paddle"
    case .mute: "Mute"
    }
  }
}
