/// Stable local RPC method names; each raw value is the method name on the wire.
package enum ApplicationServiceRPCMethod: String, CaseIterable, Sendable {
  case getStatus
  case requestRequiredAccess
  case requestAccess
  case getControllerState
  case getPacketLog
  case getVirtualOutputState
  case sendControllerOutput
  case previewPhysicalColor
  case releasePhysicalColorPreview
  case getVirtualDeviceDiagnostics
  case setVirtualHIDProfileOverride
  case resetVirtualHIDProfileOverride
  case openVirtualFeed
  case exchangeVirtualFeed
  case closeVirtualFeed
  case suspendController
  case resumeController
  case disconnectWirelessController
  case resetSettings
  case getSettings
  case setSetting
  case getAccessStatus
  case setAccessEnabled
  case grantAccess
  case revokeAccess
  case grantTokenAccess
  case setWebAccess
  case remappingMotionCalibration
  case pairRemappingJoyCons
  case unpairRemappingJoyCons
  case getRemappingSnapshot
  case getRemappingProfile
  case createRemappingProfile
  case updateRemappingProfile
  case deleteRemappingProfile
  case importRemappingProfile
  case activateRemappingProfile
  case deactivateRemappingProfile
  case deactivateRemappingProfileByID
  case getRemappingPostEventAccess
  case requestRemappingPostEventAccess
  case deleteDamagedRemappingProfile
  case resetRemappingProfileLibrary
}
