extension Button {
  /// SF Symbol name used by the Input Test button grid.
  public var systemImageName: String {
    switch self {
    case .a: "a.circle"
    case .b: "b.circle"
    case .x: "x.circle"
    case .y: "y.circle"
    case .leftBumper: "l1.button.roundedbottom.horizontal"
    case .rightBumper: "r1.button.roundedbottom.horizontal"
    case .leftStick: "l.joystick.press.down"
    case .rightStick: "r.joystick.press.down"
    case .start: "line.3.horizontal.circle"
    case .back: "rectangle.on.rectangle.circle"
    case .guide: "house.circle"
    case .dpadUp: "dpad.up.filled"
    case .dpadDown: "dpad.down.filled"
    case .dpadLeft: "dpad.left.filled"
    case .dpadRight: "dpad.right.filled"
    case .cross: "xmark.circle"
    case .circle: "circle.circle"
    case .square: "square.circle"
    case .triangle: "triangle.circle"
    case .l1: "l1.button.roundedbottom.horizontal"
    case .r1: "r1.button.roundedbottom.horizontal"
    case .l2Digital: "l2.button.roundedtop.horizontal"
    case .r2Digital: "r2.button.roundedtop.horizontal"
    case .share: "square.and.arrow.up.circle"
    case .options: "ellipsis.circle"
    case .ps: "logo.playstation"
    case .touchpad: "rectangle.roundedtop"
    case .genericButton1: "1.circle"
    case .genericButton2: "2.circle"
    case .genericButton3: "3.circle"
    case .genericButton4: "4.circle"
    case .genericButton5: "5.circle"
    case .genericButton6: "6.circle"
    case .genericButton7: "7.circle"
    case .genericButton8: "8.circle"
    }
  }

  /// A short, human-readable label for the button (e.g. `"Left Bumper (LB)"`).
  ///
  /// Used in the mapping editor and profile display.
  public var displayName: String {
    switch self {
    case .a: "A"
    case .b: "B"
    case .x: "X"
    case .y: "Y"
    case .leftBumper: "Left Bumper (LB)"
    case .rightBumper: "Right Bumper (RB)"
    case .leftStick: "Left Stick Click (LSB)"
    case .rightStick: "Right Stick Click (RSB)"
    case .start: "Start / Menu"
    case .back: "Back / View"
    case .guide: "Guide / Home"
    case .dpadUp: "D-Pad Up"
    case .dpadDown: "D-Pad Down"
    case .dpadLeft: "D-Pad Left"
    case .dpadRight: "D-Pad Right"
    case .cross: "Cross (\u{00D7})"
    case .circle: "Circle (\u{25CB})"
    case .square: "Square (\u{25A1})"
    case .triangle: "Triangle (\u{25B3})"
    case .l1: "L1"
    case .r1: "R1"
    case .l2Digital: "L2 (Digital)"
    case .r2Digital: "R2 (Digital)"
    case .share: "Share"
    case .options: "Options"
    case .ps: "PS Button"
    case .touchpad: "Touchpad Click"
    case .genericButton1: "Button 1"
    case .genericButton2: "Button 2"
    case .genericButton3: "Button 3"
    case .genericButton4: "Button 4"
    case .genericButton5: "Button 5"
    case .genericButton6: "Button 6"
    case .genericButton7: "Button 7"
    case .genericButton8: "Button 8"
    }
  }
}
